### ISSUE TITLE
Cannot log in via LDAP

### ISSUE THREAD

**Issue by kuba-orlik** [penpot/penpot#1003]
**Describe the bug**
When logging in with LDAP, I see an error: 

```
Username or password seems to be wrong.
```

The network inspector reveals an error is sent from the server:

```
Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use.
```

I suspect this might be related to the fact that my LDAP server stores multiple email addresses per account?

**To Reproduce**
1.  Create an LDAP account with multiple email addresses with your LDAP provider
2.  Open the login form
3.  Enter your details
4.  See the error

**Expected behavior**
I expect to be able to log in using one of the email addresses assigned to me in the LDAP server

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser Firefox
-   Version 89

**Environment (please complete the following information):**

Self-hosted instance. 

* Debian 10. 
* Docker version 20.10.6, build 370c289
* docker-compose version 1.29.2, build 5becea4c
* Image: the official images mentioned in the docs

**Backend Stack Trace (if self-hosted)**
Nothing related shows up when I run `docker-compose logs -f`

**Comment by niwinz** [comment]
Would be awesome to know the exact version you are running of penpot, and the backend docker image tag/id.

**Comment by kuba-orlik** [comment]
Sure thing :) 

```
penpotapp/exporter   latest    ea7f154942f6   5 days ago    986MB
penpotapp/frontend   latest    adf60ae90094   5 days ago    213MB
postgres             13        293e4ed402ba   2 weeks ago   315MB
redis                6         bc8d70f9ef6c   2 weeks ago   105MB
penpotapp/backend    latest    6659cd58c3cd   3 weeks ago   728MB
```

**Comment by kuba-orlik** [comment]
I'll add that the "Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use." error appears only upon entering valid credentials. If I enter invalid credentials, I get the regular `~:wrong-credentials`

I've also tried adding the main email address of the LDAP user to a different field (`carLicense`) on the LDAP-server side, and changing `PENPOT_LDAP_ATTRS_EMAIL` to `carLicense`, but that brings me back to "invalid credentials"

**Comment by niwinz** [comment]
This looks like a bug, but I need to confirm.

**Comment by niwinz** [comment]
I'm unable to locate the image with this short hash `6659cd58c3cd`, and it does not matches the latest image id. Can you try to pull the latest images and check. I have tried it locally and it worked correctly, so I need to discard other issues. Maybe the bug is already fixes in the latest image published right now on the dockerhub.

**Comment by kuba-orlik** [comment]
Woah, I've pulled the image 3 hours ago on a fresh machine, thought it's the newest one - will try and let you know!

**Comment by kuba-orlik** [comment]
...that's weird. I've pulled the images and docker said there's nothing to change.

I've set image version to `1.6.1-alpha` manually and it shows it's the same version I've been using... while in fact dockerhub shows a different hash for that image:

```
REPOSITORY           TAG           IMAGE ID       CREATED       SIZE
penpotapp/exporter   latest        ea7f154942f6   5 days ago    986MB
penpotapp/frontend   latest        adf60ae90094   5 days ago    213MB
postgres             13            293e4ed402ba   2 weeks ago   315MB
redis                6             bc8d70f9ef6c   2 weeks ago   105MB
penpotapp/backend    1.6.1-alpha   6659cd58c3cd   3 weeks ago   728MB
penpotapp/backend    latest        6659cd58c3cd   3 weeks ago   728MB
```

**Comment by niwinz** [comment]
Very strange, in any case, let me publish a new image right now with latest fixes.

**Comment by niwinz** [comment]
Published latest images `1.6.3-alpha`

**Comment by kuba-orlik** [comment]
Pulled the `1.6.3-alpha` image. The issue still persists - with the same behavior and errors

**Comment by niwinz** [comment]
Ok, looks like something related to your environent and something we are not handling correctly. Let me research what can be the cause. There are no exception stack traces on backend logs that can help find the exact error?

**Comment by kuba-orlik** [comment]
Thank you for your patience! 😇 

I double checked and there in fact is a stack trace in the logs, here it is:

```
[2021-06-01 14:19:11.117] [qtp1192672269-32] E app.http.errors - error-id="55b242d0-c2e4-11eb-acc4-a8d9bb4ee4df" error-message="Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use." hint="psql exception" sql-state="07006"
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use.
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:1011) ~[postgresql-42.2.20.jar:42.2.20]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:?]
	at next.jdbc.prepare$eval5793$fn__5794.invokePrim(prepare.clj:42) ~[?:?]
	at next.jdbc.prepare$eval5793$fn__5794.invoke(prepare.clj) ~[?:?]
	at next.jdbc.prepare$eval5768$fn__5769$G__5759__5778.invoke(prepare.clj:29) ~[?:?]
	at next.jdbc.prepare$set_parameters.invokeStatic(prepare.clj:55) ~[?:?]
	at next.jdbc.prepare$set_parameters.invoke(prepare.clj:48) ~[?:?]
	at next.jdbc.prepare$create.invokeStatic(prepare.clj:144) ~[?:?]
	at next.jdbc.prepare$create.invoke(prepare.clj:83) ~[?:?]
	at next.jdbc.result_set$eval6361$fn__6366.invoke(result_set.clj:897) ~[?:?]
	at next.jdbc.protocols$eval5642$fn__5643$G__5631__5652.invoke(protocols.clj:33) ~[?:?]
	at next.jdbc$execute_one_BANG_.invokeStatic(jdbc.clj:266) ~[?:?]
	at next.jdbc$execute_one_BANG_.invoke(jdbc.clj:250) ~[?:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:160) ~[clojure-1.10.3.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.3.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:671) ~[clojure-1.10.3.jar:?]
	at clojure.core$apply.invoke(core.clj:662) ~[clojure-1.10.3.jar:?]
	at app.metrics$wrap_counter$fn__4202.doInvoke(metrics.clj:215) ~[?:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.10.3.jar:?]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:436) ~[clojure-1.10.3.jar:?]
	at app.db$exec_one_BANG_.invokeStatic(db.clj:194) ~[?:?]
	at app.db$exec_one_BANG_.invoke(db.clj:191) ~[?:?]
	at app.db$exec_one_BANG_.invokeStatic(db.clj:192) ~[?:?]
	at app.db$exec_one_BANG_.invoke(db.clj:191) ~[?:?]
	at app.rpc.queries.profile$retrieve_profile_data_by_email.invokeStatic(profile.clj:101) ~[?:?]
	at app.rpc.queries.profile$retrieve_profile_data_by_email.invoke(profile.clj:98) ~[?:?]
	at app.rpc.mutations.profile$login_or_register.invokeStatic(profile.clj:356) ~[?:?]
	at app.rpc.mutations.profile$login_or_register.invoke(profile.clj:321) ~[?:?]
	at app.rpc.mutations.ldap$sm$login_with_ldap.invokeStatic(ldap.clj:53) ~[?:?]
	at app.rpc.mutations.ldap$sm$login_with_ldap.invoke(ldap.clj:46) ~[?:?]
	at app.rpc$wrap_with_rlimits$fn__28173.invoke(rpc.clj:85) ~[?:?]
	at app.metrics$wrap_summary$fn__4227.invoke(metrics.clj:264) ~[?:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.10.3.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.3.jar:?]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:421) ~[clojure-1.10.3.jar:?]
	at app.rpc$wrap_impl$fn__28183.invoke(rpc.clj:103) ~[?:?]
	at app.rpc$rpc_mutation_handler.invokeStatic(rpc.clj:59) ~[?:?]
	at app.rpc$rpc_mutation_handler.invoke(rpc.clj:50) ~[?:?]
	at app.rpc$eval28229$fn__28230$fn__28233.invoke(rpc.clj:183) ~[?:?]
	at app.http.session$middleware$fn__26353.invoke(session.clj:70) ~[?:?]
	at ring.middleware.cookies$wrap_cookies$fn__28981.invoke(cookies.clj:214) ~[?:?]
	at app.http.middleware$wrap_errors$fn__29216.invoke(middleware.clj:109) ~[?:?]
	at app.http.middleware$wrap_parse_request_body$fn__29206.invoke(middleware.clj:56) ~[?:?]
	at ring.middleware.keyword_params$wrap_keyword_params$fn__29027.invoke(keyword_params.clj:53) ~[?:?]
	at ring.middleware.multipart_params$wrap_multipart_params$fn__29159.invoke(multipart_params.clj:171) ~[?:?]
	at ring.middleware.params$wrap_params$fn__29183.invoke(params.clj:67) ~[?:?]
	at app.http.middleware$wrap_format_response_body$fn__29212.invoke(middleware.clj:97) ~[?:?]
	at app.http.middleware$wrap_etag$fn__29230.invoke(middleware.clj:149) ~[?:?]
	at reitit.ring$ring_handler$fn__31047.invoke(ring.cljc:329) ~[?:?]
	at app.http.middleware$wrap_server_timing$fn__29193.invoke(middleware.clj:26) ~[?:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.3.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.3.jar:?]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.3.jar:?]
	at app.http$router_handler$fn__31691.invoke(http.clj:90) ~[?:?]
	at ring.adapter.jetty9$proxy_handler$fn__31592.invoke(jetty9.clj:54) ~[?:?]
	at ring.adapter.jetty9.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:171) ~[jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:399) ~[jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:656) [jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:391) [jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:284) [jetty-server-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) [jetty-io-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [jetty-io-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101) [jetty-io-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.2.jar:10.0.2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.2.jar:10.0.2]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by niwinz** [comment]
Nice, thank you!

**Comment by niwinz** [comment]
Looks like in this case the LDAP server is returing something different to string (an object/hash-map) for the `email` attr. I don't know how can I help here, your LDAP server should return an attribute with plain email as string and you need to use the `PENPOT_LDAP_ATTRS_EMAIL` environment variable to configure for use this attribute. 
I'm not LDAP expert so I don't know how it can be done from the LDAP side...

**Comment by kuba-orlik** [comment]
I think that the server returns a list of email addresses, as I have multiple email addresses attached to that LDAP account:

![image](https://user-images.githubusercontent.com/2697916/120350719-86dcd300-c2ff-11eb-8d40-79cdc0625056.png)

I managed to find a workoaround. I've added another field to my LDAP user entry on the LDAP server side: `carLicense`, and entered the email there.

Then I've changed `PENPOT_LDAP_ATTRS_EMAIL` to `carLicense`. What's weird is that now the login works, but I have to log in with one of my emails stored in `email`, not the email stored in `carLicense`.

So I guess we have two issues at hand:

1. LDAP login doesn't work when the server returns multiple addreses (auth works, but the database tries to store an array instead of e.g. only the first element of that array)
2. LDAP doesn't use the value of the `PENPOT_LDAP_ATTRS_EMAIL`  field for login. One has to use the hard-coded `email` field for login.

**Comment by niwinz** [comment]
The real problem here is that the penpot account uses email as the identifier. There are no technical problem if LDAP returns multiple emails, we just can add a specific check that if the returned value is a vector, just retrieve the matched email from the list. The real problem is that if you try to login with an other email that is part of the same LDAP account will create a separated user on penpot. If this is not a problem, we just can add a specific check for this case.

**Comment by niwinz** [comment]
This will be solved in the next release. In other words: penpot will be compatible with LDAP accounts with more than one email by default.
