### ISSUE TITLE
LDAP auth error: Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector.

### ISSUE THREAD

**Issue by berggy** [penpot/penpot#1146]
**Describe the bug**
Installed with docker(https://help.penpot.app/technical-guide/getting-started/), and LDAP configed.
When i login, the error is:
`
{"~:type":"~:server-error","~:code":"~:psql-exception","~:hint":"Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use.","~:state":"07006"}
`

**To Reproduce**
1.  Install docker and start the containers
`
wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml

wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/config.env

docker-compose -p penpot -f docker-compose.yaml up -d
`

the config.env has the following ldap configuration
# LDAP
 PENPOT_LDAP_HOST=192.168.1.xx --internal IP, the container can access.
 PENPOT_LDAP_PORT=389
 PENPOT_LDAP_SSL=false
 PENPOT_LDAP_STARTTLS=false
 PENPOT_LDAP_BASE_DN= wowo*v*
 PENPOT_LDAP_BIND_DN= wowo*v*
 PENPOT_LDAP_BIND_PASSWORD=wowo*v*
 PENPOT_LDAP_ATTRS_USERNAME=uid
 PENPOT_LDAP_ATTRS_EMAIL=mail
 PENPOT_LDAP_ATTRS_FULLNAME=cn
 PENPOT_LDAP_ATTRS_PHOTO=jpegPhoto
 PENPOT_LOGIN_WITH_LDAP=true

2.  The LDAP configuration is right, else the error is different.
3. Both LDAP and demo login do not work.
the demo login returns
`
{"~:email":"demo-1628902920794.demo@example.com","~:password":"rcA0k6-IDAsItk_NRSTpVQ"}
`
and
`
{"~:type":"~:validation","~:code":"~:wrong-credentials"}
`

**Expected behavior**
It looks like that when creating a internal user record in postgres database according to the loginning user, the INSERT operation can not be constructed correctly.

**Screenshots**
[the screenshot may not be seen](http://www.seuoa.com:8086/s/FNi5AjSZ6T5aCei)

**Environment (please complete the following information):**

# docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~18.04.1
 Built:             Wed Aug  4 22:43:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~18.04.1
  Built:            Wed Aug  4 19:22:59 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          1.0.0~rc95-0ubuntu1~18.04.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

Specify if using SAAS (https://design.penpot.app) or self-hosted instance.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: (Ubuntu 18.04)

# docker logs penpot_penpot-backend_1, HERE IT IS
...
[2021-08-14 01:07:36.962] [qtp1594409085-32] E app.http.errors - error-id="038cf800-fc9c-11eb-ab40-0f5dba55a847" error-message="Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use." hint="psql exception" sql-state="07006"
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use.
        at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:1011) ~[postgresql-42.2.20.jar:42.2.20]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:?]
        at next.jdbc.prepare$eval5990$fn__5991.invokePrim(prepare.clj:42) ~[?:?]
        at next.jdbc.prepare$eval5990$fn__5991.invoke(prepare.clj) ~[?:?]
        at next.jdbc.prepare$eval5965$fn__5966$G__5956__5975.invoke(prepare.clj:29) ~[?:?]
        at next.jdbc.prepare$set_parameters.invokeStatic(prepare.clj:55) ~[?:?]
        at next.jdbc.prepare$set_parameters.invoke(prepare.clj:48) ~[?:?]
        at next.jdbc.prepare$create.invokeStatic(prepare.clj:144) ~[?:?]
        at next.jdbc.prepare$create.invoke(prepare.clj:83) ~[?:?]
        at next.jdbc.result_set$eval6545$fn__6550.invoke(result_set.clj:851) ~[?:?]
        at next.jdbc.protocols$eval5839$fn__5840$G__5828__5849.invoke(protocols.clj:33) ~[?:?]
        at next.jdbc$execute_one_BANG_.invokeStatic(jdbc.clj:266) ~[?:?]
        at next.jdbc$execute_one_BANG_.invoke(jdbc.clj:250) ~[?:?]
        at app.metrics$wrap_counter$fn__4246.invoke(metrics.clj:215) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:160) ~[clojure-1.10.3.jar:?]
        at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.3.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:436) ~[clojure-1.10.3.jar:?]
        at app.db$exec_one_BANG_.invokeStatic(db.clj:195) ~[?:?]
        at app.db$exec_one_BANG_.invoke(db.clj:192) ~[?:?]
        at app.db$insert_BANG_.invokeStatic(db.clj:200) ~[?:?]
        at app.db$insert_BANG_.invoke(db.clj:197) ~[?:?]
        at app.db$insert_BANG_.invokeStatic(db.clj:198) ~[?:?]
        at app.db$insert_BANG_.invoke(db.clj:197) ~[?:?]
        at app.rpc.mutations.profile$create_profile.invokeStatic(profile.clj:256) ~[?:?]
        at app.rpc.mutations.profile$create_profile.invoke(profile.clj:219) ~[?:?]
        at app.rpc.mutations.ldap$login_or_register.invokeStatic(ldap.clj:120) ~[?:?]
        at app.rpc.mutations.ldap$login_or_register.invoke(ldap.clj:110) ~[?:?]
        at app.rpc.mutations.ldap$sm$login_with_ldap$fn__38729.invoke(ldap.clj:60) ~[?:?]
        at next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72) ~[?:?]
        at next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51) ~[?:?]
        at next.jdbc.transaction$eval7130$fn__7131.invoke(transaction.clj:136) ~[?:?]
        at next.jdbc.protocols$eval5929$fn__5930$G__5920__5939.invoke(protocols.clj:57) ~[?:?]
        at next.jdbc$transact.invokeStatic(jdbc.clj:342) ~[?:?]
        at next.jdbc$transact.invoke(jdbc.clj:334) ~[?:?]
        at app.rpc.mutations.ldap$sm$login_with_ldap.invokeStatic(ldap.clj:52) ~[?:?]
        at app.rpc.mutations.ldap$sm$login_with_ldap.invoke(ldap.clj:50) ~[?:?]
        at app.rpc$wrap_with_rlimits$fn__28321.invoke(rpc.clj:89) ~[?:?]
        at app.metrics$wrap_summary$fn__4271.invoke(metrics.clj:270) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.10.3.jar:?]
        at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.3.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:421) ~[clojure-1.10.3.jar:?]
        at app.rpc$wrap_impl$fn__28331.invoke(rpc.clj:111) ~[?:?]
        at app.rpc$rpc_mutation_handler.invokeStatic(rpc.clj:63) ~[?:?]
        at app.rpc$rpc_mutation_handler.invoke(rpc.clj:51) ~[?:?]
        at app.rpc$eval28376$fn__28377$fn__28380.invoke(rpc.clj:197) ~[?:?]
        at app.http.session$middleware$fn__26517.invoke(session.clj:70) ~[?:?]
        at ring.middleware.cookies$wrap_cookies$fn__29359.invoke(cookies.clj:214) ~[?:?]
        at app.http.middleware$wrap_errors$fn__29597.invoke(middleware.clj:126) ~[?:?]
        at app.http.middleware$wrap_parse_request_body$fn__29584.invoke(middleware.clj:57) ~[?:?]
        at ring.middleware.keyword_params$wrap_keyword_params$fn__29405.invoke(keyword_params.clj:53) ~[?:?]
        at ring.middleware.multipart_params$wrap_multipart_params$fn__29537.invoke(multipart_params.clj:171) ~[?:?]
        at ring.middleware.params$wrap_params$fn__29561.invoke(params.clj:67) ~[?:?]
        at app.http.middleware$wrap_format_response_body$fn__29593.invoke(middleware.clj:114) ~[?:?]
        at reitit.ring$ring_handler$fn__31278.invoke(ring.cljc:329) ~[?:?]
        at app.http.middleware$wrap_server_timing$fn__29571.invoke(middleware.clj:27) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.3.jar:?]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.3.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.3.jar:?]
        at app.http$router_handler$fn__31845.invoke(http.clj:90) ~[?:?]
        at ring.adapter.jetty9$proxy_handler$fn__31746.invoke(jetty9.clj:54) ~[?:?]
        at ring.adapter.jetty9.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) ~[?:?]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:171) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:399) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:656) [jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:391) [jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:284) [jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) [jetty-io-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [jetty-io-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101) [jetty-io-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.2.jar:10.0.2]
        at java.lang.Thread.run(Thread.java:831) [?:?]

# docker logs penpot_penpot-frontend_1
[2021-08-14T00:52:35+00:00] Updating Allow Demo Users: true
[2021-08-14T00:52:35+00:00] Updating Login with LDAP: true
[2021-08-14T00:52:35+00:00] Updating Registration Enabled: true
192.168.2.132 - - [14/Aug/2021:00:54:30 +0000] "GET / HTTP/1.1" 200 122878 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:00:54:30 +0000] "GET /js/config.js?ts=1628082855397 HTTP/1.1" 200 261 "http://192.168.1.xx:8099/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:00:54:30 +0000] "GET /js/polyfills.js?ts=1628082855397 HTTP/1.1" 304 0 "http://192.168.1.xx:8099/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:00:54:30 +0000] "GET /js/shared.326c52604.js HTTP/1.1" 304 0 "http://192.168.1.xx:8099/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:00:54:30 +0000] "GET /js/main.326c52604.js HTTP/1.1" 304 0 "http://192.168.1.xx:8099/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:00:54:30 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:00:54:30 +0000] "GET /images/favicon.png HTTP/1.1" 200 12521 "http://192.168.1.xx:8099/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:00:54:42 +0000] "POST /api/rpc/mutation/login-with-ldap HTTP/1.1" 500 250 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:01:02:01 +0000] "POST /api/rpc/mutation/create-demo-profile HTTP/1.1" 200 114 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:01:02:01 +0000] "POST /api/rpc/mutation/login HTTP/1.1" 400 67 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:01:02:13 +0000] "POST /api/rpc/mutation/login-with-ldap HTTP/1.1" 500 250 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.2.132 - - [14/Aug/2021:01:07:36 +0000] "POST /api/rpc/mutation/login-with-ldap HTTP/1.1" 500 250 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"

**Comment by niwinz** [comment]
This error is caused because fullname (or any other) attribute returns a collection of values instead of a single value.
I will implement proper validation and better error reporting but I think this should be fixed from the user side. LDAP is so flexible that it is impossible implement all the cases of all LDAP setups. 

Each attribute should be a single value.

**Comment by niwinz** [comment]
The error reporting and the demo user creation will be fixed as soon as #1150  is merged and we generate the new images.
