### ISSUE TITLE
Installation error using docker

### ISSUE THREAD

**Issue by Hamdy** [penpot/penpot#307]
Hi , Docker installation not working smoothly, is there something I'm missing? or am I using wrong branch?

Branch `develop`
Command `./manage.sh run-devenv`

**`gulp`**
```
Error on reading manifest, using default.
[14:57:52] 'template:main' errored after 8.07 ms
[14:57:52] Error: ENOENT: no such file or directory, open '/home/uxbox/uxbox/frontend/resources/public/js/config.js'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1362:35)
    at /home/uxbox/uxbox/frontend/gulpfile.js:170:8
    at template:main (/home/uxbox/uxbox/frontend/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (/home/uxbox/uxbox/frontend/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[14:57:52] 'templates' errored after 57 ms
[14:57:52] 'build' errored after 58 ms
[14:57:52] 'watch' errored after 92 ms

```
**`shadow watch`**

```
shadow-cljs - config: /home/uxbox/uxbox/frontend/shadow-cljs.edn
shadow-cljs - starting via "clojure"
Error building classpath. Failed to resolve version for binaryage:devtools:jar:RELEASE: Could not find metadata binaryage:devtools/maven-metadata.xml in local (/home/uxbox/.m2/repository)               
org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for binaryage:devtools:jar:RELEASE: Could not find metadata binaryage:devtools/maven-metadata.xml in local (/home/uxbox/.m2/repository)
        at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:276)                                                                                    
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveVersion(DefaultRepositorySystem.java:240)                                                                                      
        at clojure.tools.deps.alpha.extensions.maven$eval956$fn__959.invoke(maven.clj:42)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at clojure.tools.deps.alpha$canonicalize_deps$fn__739.invoke(alpha.clj:332)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8140.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$reduce.invoke(core.clj:6810)
        at clojure.tools.deps.alpha$canonicalize_deps.invokeStatic(alpha.clj:331)
        at clojure.tools.deps.alpha$canonicalize_deps.invoke(alpha.clj:329)
        at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:462)
        at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:443)
        at clojure.tools.deps.alpha$calc_basis.invokeStatic(alpha.clj:570)
        at clojure.tools.deps.alpha$calc_basis.invoke(alpha.clj:545)
        at clojure.tools.deps.alpha.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:86)                                                                                                  
        at clojure.tools.deps.alpha.script.make_classpath2$run_core.invoke(make_classpath2.clj:56)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:109)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:103)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:158)                                                                                                    
        at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:128)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
Caused by: org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata binaryage:devtools/maven-metadata.xml in local (/home/uxbox/.m2/repository)                                     
        at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:220)                                                                                             
        at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:181)                                                                                     
        at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:213)                                                                                    
        ... 32 more
uxbox@uxbox-devenv-main:~/uxbox/frontend/ >

```
**`Backend`**
```
uxbox@uxbox-devenv-main:~/uxbox/backend/ > ./scripts/start-dev
Loading fixtures...
Error building classpath. Failed to resolve version for clj-kondo:clj-kondo:jar:RELEASE: Could not find metadata clj-kondo:clj-kondo/maven-metadata.xml in local (/home/uxbox/.m2/repository)             
org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for clj-kondo:clj-kondo:jar:RELEASE: Could not find metadata clj-kondo:clj-kondo/maven-metadata.xml in local (/home/uxbox/.m2/repository)
        at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:276)                                                                                    
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveVersion(DefaultRepositorySystem.java:240)                                                                                      
        at clojure.tools.deps.alpha.extensions.maven$eval956$fn__959.invoke(maven.clj:42)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at clojure.tools.deps.alpha$canonicalize_deps$fn__739.invoke(alpha.clj:332)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8140.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$reduce.invoke(core.clj:6810)
        at clojure.tools.deps.alpha$canonicalize_deps.invokeStatic(alpha.clj:331)
        at clojure.tools.deps.alpha$canonicalize_deps.invoke(alpha.clj:329)
        at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:462)
        at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:443)
        at clojure.tools.deps.alpha$calc_basis.invokeStatic(alpha.clj:570)
        at clojure.tools.deps.alpha$calc_basis.invoke(alpha.clj:545)
        at clojure.tools.deps.alpha.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:86)                                                                                                  
        at clojure.tools.deps.alpha.script.make_classpath2$run_core.invoke(make_classpath2.clj:56)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:109)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:103)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:158)                                                                                                    
        at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:128)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
Caused by: org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata clj-kondo:clj-kondo/maven-metadata.xml in local (/home/uxbox/.m2/repository)                                    
        at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:220)                                                                                             
        at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:181)                                                                                     
        at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:213)                                                                                    
        ... 32 more
```
**`exporter`**

```
uxbox@uxbox-devenv-main:~/uxbox/exporter/ > npx shadow-cljs watch main                                                                                                                             [22/120]
shadow-cljs - config: /home/uxbox/uxbox/exporter/shadow-cljs.edn                                                                                                                                           
shadow-cljs - updating dependencies                                                                                                                                                                        
shadow-cljs - dependency update failed - Failed to collect dependencies at thheller:shadow-cljs:jar:aot:2.10.19                                                                                            
DependencyResolutionException Failed to collect dependencies at thheller:shadow-cljs:jar:aot:2.10.19                                                                                                       
        org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:351)                                                                                    
        jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)                                                                                                           
        jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                                                                                            
        jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                                                                                    
        java.lang.reflect.Method.invoke (Method.java:564)                                                                                                                                                  
        clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)                                                                                                                                   
        clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)                                                                                                                                   
        cemerick.pomegranate.aether/resolve-dependencies* (aether.clj:806)                                                                                                                                 
        cemerick.pomegranate.aether/resolve-dependencies* (aether.clj:707)                                                                                                                                 
        clojure.core/apply (core.clj:665)                                                                                                                                                                  
        clojure.core/apply (core.clj:660)
        cemerick.pomegranate.aether/resolve-dependencies (aether.clj:815)
Caused by:
DependencyCollectionException Failed to collect dependencies at thheller:shadow-cljs:jar:aot:2.10.19
        org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:293)
        org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:307)
        jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
Caused by:
ArtifactDescriptorException Failed to read artifact descriptor for thheller:shadow-cljs:jar:aot:2.10.19
        org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom (DefaultArtifactDescriptorReader.java:276)
        org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor (DefaultArtifactDescriptorReader.java:192)
```

**Comment by niwinz** [comment]
Hello @Hamdy 

You are using the correct branch, but in any case is a development branch and can have broken code.
Looking the stack traces, with the exception of the "gulp" task the rest of strack traces seems related to some asumptions that are not meet on your pc (you didn't have the `~/.m2/` directory previously). This is a **known issue**. A simmilar issue is found in the gulp trace (it expects some directory exists but on new installation it does not exists). I'll try to fix this issues soon.
 
In any case devenv is not a good approach for test the platform. We are now working in a solution for this, for provide a simplier way to get the application up and running. As soon as we have solution to this i will ping you here.

**Comment by AtjonTV** [comment]
Please ping me too when a solution is in place ;D

**Comment by niwinz** [comment]
Look at #310 @AtjonTV

**Comment by Hamdy** [comment]
Hi
container `uxbox-devenv` seemd to stop immediately after starting

```
hamdy@myth:~/projsects/uxbox$ ./manage.sh run-devenv 
uxbox-devenv-postgres is up-to-date
uxbox-devenv-smtp is up-to-date
uxbox-devenv-redis is up-to-date
Starting uxbox-devenv-main ... done
cannot exec in a stopped state: unknown

```

and here's the logs from container
```
hamdy@myth:~/projsects/uxbox$ docker logs 68d24095d78f
+ sudo cp /root/.bashrc /home/uxbox/.bashrc
+ sudo cp /root/.vimrc /home/uxbox/.vimrc
+ sudo cp /root/.tmux.conf /home/uxbox/.tmux.conf
+ sudo chown uxbox:users /home/uxbox
+ exec /home/init.sh
+ sudo cp /root/.bashrc /home/uxbox/.bashrc
+ sudo cp /root/.vimrc /home/uxbox/.vimrc
+ sudo cp /root/.tmux.conf /home/uxbox/.tmux.conf
+ sudo chown uxbox:users /home/uxbox
+ exec /home/init.sh
+ sudo cp /root/.bashrc /home/uxbox/.bashrc
+ sudo cp /root/.vimrc /home/uxbox/.vimrc
+ sudo cp /root/.tmux.conf /home/uxbox/.tmux.conf
+ sudo chown uxbox:users /home/uxbox
+ exec /home/init.sh
+ sudo cp /root/.bashrc /home/uxbox/.bashrc
+ sudo cp /root/.vimrc /home/uxbox/.vimrc
+ sudo cp /root/.tmux.conf /home/uxbox/.tmux.conf
+ sudo chown uxbox:users /home/uxbox
+ exec /home/init.sh
+ sudo cp /root/.bashrc /home/uxbox/.bashrc
+ sudo cp /root/.vimrc /home/uxbox/.vimrc
+ sudo cp /root/.tmux.conf /home/uxbox/.tmux.conf
+ sudo chown uxbox:users /home/uxbox
+ exec /home/init.sh
```

**Comment by niwinz** [comment]
Yes there are some issues on devenv, but right now development branch should have this fixed, please rebuild the devenv. In any case i recommend using the testenv for not development purposes https://github.com/uxbox/uxbox/blob/develop/docs/01-Development-Environment.md#start-the-testenv (merged this days)

**Comment by AtjonTV** [comment]
May I note that UXBOX from develop is quite unstable. As soon as I add a Lable anywhere I only get a Application internal error and cant open the layout anymore.

This is obviously a different issue then what this ticket is about, I just wanted to inform you without opening a extra ticket for it ;D

Sadly for now I will have to keep my Windows 10 VM running on my Gentoo Linux to use Adobe XD for making UI mockups. Hopefully UXBOX is soon able to change this situation of mine :D

**Comment by niwinz** [comment]
@AtjonTV thanks for the report; we will look at this asap. In any case, this is expected, is development branch and right now, we have merged a big refactor that has left some parts of the code broken.

**Comment by AtjonTV** [comment]
I know. I tried to use something and I got a `TODO: this is brocken` popup .. dont know anymore where that was though xD
