### ISSUE TITLE
Unable to authenticate with LDAP

### ISSUE THREAD

**Issue by ldidry** [penpot/penpot#651]
**Describe the bug**
Our LDAP disallows anonymous bind (`olcDisallows: bind_anon`) and requires an authentication (`olcRequires: authc`) and Penpot fails to authenticate users with LDAP because of that.

**To Reproduce**
Try to authenticate with a LDAP without anonymous bind.

**Expected behavior**
I should be able to login with LDAP even it disallows anonymous bind.

**Environment (please complete the following information):**
Self-hosted instance

-   OS Version: Debian 10

Also provide Docker commands or docker-compose file if possible.

-   Docker / Docker-compose Version: Docker version 20.10.3, build 48d30b5 / docker-compose version 1.28.2, build 67630359
-   Image : the one created by your docker-compose.yaml
- 
Here is my LDAP configuration set in `docker-compose.yaml`:

<details>

```
      - PENPOT_LDAP_AUTH_HOST=ldap.example.org
      - PENPOT_LDAP_AUTH_PORT=636
      - PENPOT_LDAP_BIND_DN=uid=ldap,ou=users,dc=example.org,dc=local
      - PENPOT_LDAP_BIND_PASSWORD=foobarbaz
      - PENPOT_LDAP_AUTH_SSL=true
      - PENPOT_LDAP_AUTH_STARTTLS=false
      - PENPOT_LDAP_AUTH_BASE_DN=ou=users,dc=example.org,dc=local
      - PENPOT_LDAP_AUTH_USER_QUERY=(|(uid=$$username)(mail=$$username))
      - PENPOT_LDAP_AUTH_USERNAME_ATTRIBUTE=uid
      - PENPOT_LDAP_AUTH_EMAIL_ATTRIBUTE=mail
      - PENPOT_LDAP_AUTH_FULLNAME_ATTRIBUTE=displayName
      - PENPOT_LDAP_AUTH_AVATAR_ATTRIBUTE=jpegPhoto
```

</details>

(Note that I had to double the `$` symbol to have `PENPOT_LDAP_AUTH_USER_QUERY=(|(uid=$username)(mail=$username))` in the backend container instead of `PENPOT_LDAP_AUTH_USER_QUERY=(|(uid=)(mail=))`)

**Backend Stack Trace (if self-hosted)**

<details>

```
[qtp1402467446-29] E app.http.auth.ldap - Cannot connect to LDAP ldap.example.org:636                                                                                               [207/560]
com.unboundid.ldap.sdk.LDAPBindException: anonymous bind disallowed
        at com.unboundid.ldap.sdk.LDAPConnection.bind(LDAPConnection.java:2334) ~[unboundid-ldapsdk-5.0.1.jar:5.0.1]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167) ~[clojure-1.10.2.jar:?]
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102) ~[clojure-1.10.2.jar:?]
        at clj_ldap.client$connect_to_host.invokeStatic(client.clj:171) ~[?:?]
        at clj_ldap.client$connect_to_host.invoke(client.clj:166) ~[?:?]
        at clj_ldap.client$connect.invokeStatic(client.clj:377) ~[?:?]
        at clj_ldap.client$connect.invoke(client.clj:343) ~[?:?]
        at app.http.auth.ldap$create_connection$fn__28258.invoke(ldap.clj:101) ~[?:?]
        at clojure.lang.Delay.deref(Delay.java:42) ~[clojure-1.10.2.jar:?]
        at clojure.core$deref.invokeStatic(core.clj:2324) ~[clojure-1.10.2.jar:?]
        at clojure.core$deref.invoke(core.clj:2310) ~[clojure-1.10.2.jar:?]
        at app.http.auth.ldap$authenticate.invokeStatic(ldap.clj:109) ~[?:?]
        at app.http.auth.ldap$authenticate.invoke(ldap.clj:107) ~[?:?]
        at app.http.auth.ldap$eval28241$fn__28243$fn__28245.invoke(ldap.clj:62) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
        at ring.middleware.cookies$wrap_cookies$fn__20710.invoke(cookies.clj:214) ~[?:?]
        at app.http.middleware$wrap_errors$fn__20945.invoke(middleware.clj:109) ~[?:?]
        at app.http.middleware$wrap_parse_request_body$fn__20935.invoke(middleware.clj:56) ~[?:?]
        at ring.middleware.keyword_params$wrap_keyword_params$fn__20756.invoke(keyword_params.clj:53) ~[?:?]
        at ring.middleware.multipart_params$wrap_multipart_params$fn__20888.invoke(multipart_params.clj:171) ~[?:?]
        at ring.middleware.params$wrap_params$fn__20912.invoke(params.clj:67) ~[?:?]
        at app.http.middleware$wrap_format_response_body$fn__20941.invoke(middleware.clj:97) ~[?:?]
        at reitit.ring$ring_handler$fn__30123.invoke(ring.cljc:326) ~[?:?]
        at app.http.middleware$wrap_server_timing$fn__20922.invoke(middleware.clj:26) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
        at app.http$eval30796$fn__30797$fn__30798.invoke(http.clj:103) ~[?:?]
        at ring.adapter.jetty9$proxy_handler$fn__30670.invoke(jetty9.clj:54) ~[?:?]
        at ring.adapter.jetty9.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) ~[?:?]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

</details>

When I remove `olcDisallows: bind_anon` from the configuration of my LDAP server:

<details>

```
[qtp1402467446-23] E app.http.errors - Internal error: authentication required (id: f1c13dc0-7050-11eb-b54f-1779431d3823)                                                             [108/560]
com.unboundid.ldap.sdk.LDAPSearchException: authentication required
        at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3833) ~[unboundid-ldapsdk-5.0.1.jar:5.0.1]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.search(AbstractConnectionPool.java:2071) ~[unboundid-ldapsdk-5.0.1.jar:5.0.1]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.search(AbstractConnectionPool.java:1571) ~[unboundid-ldapsdk-5.0.1.jar:5.0.1]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167) ~[clojure-1.10.2.jar:?]
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102) ~[clojure-1.10.2.jar:?]
        at clj_ldap.client$search_results.invokeStatic(client.clj:290) ~[?:?]
        at clj_ldap.client$search_results.invoke(client.clj:287) ~[?:?]
        at clj_ldap.client$search.invokeStatic(client.clj:521) ~[?:?]
        at clj_ldap.client$search.invoke(client.clj:507) ~[?:?]
        at app.http.auth.ldap$authenticate.invokeStatic(ldap.clj:118) ~[?:?]
        at app.http.auth.ldap$authenticate.invoke(ldap.clj:107) ~[?:?]
        at app.http.auth.ldap$eval28241$fn__28243$fn__28245.invoke(ldap.clj:62) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
        at ring.middleware.cookies$wrap_cookies$fn__20710.invoke(cookies.clj:214) ~[?:?]
        at app.http.middleware$wrap_errors$fn__20945.invoke(middleware.clj:109) ~[?:?]
        at app.http.middleware$wrap_parse_request_body$fn__20935.invoke(middleware.clj:56) ~[?:?]
        at ring.middleware.keyword_params$wrap_keyword_params$fn__20756.invoke(keyword_params.clj:53) ~[?:?]
        at ring.middleware.multipart_params$wrap_multipart_params$fn__20888.invoke(multipart_params.clj:171) ~[?:?]
        at ring.middleware.params$wrap_params$fn__20912.invoke(params.clj:67) ~[?:?]
        at app.http.middleware$wrap_format_response_body$fn__20941.invoke(middleware.clj:97) ~[?:?]
        at reitit.ring$ring_handler$fn__30123.invoke(ring.cljc:326) ~[?:?]
        at app.http.middleware$wrap_server_timing$fn__20922.invoke(middleware.clj:26) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.2.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
        at app.http$eval30796$fn__30797$fn__30798.invoke(http.clj:103) ~[?:?]
        at ring.adapter.jetty9$proxy_handler$fn__30670.invoke(jetty9.clj:54) ~[?:?]
        at ring.adapter.jetty9.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) ~[?:?]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) ~[jetty-server-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
        at java.lang.Thread.run(Thread.java:832) [?:?
```

</details>

**Comment by ldidry** [comment]
Note: to disallow anonymous bind, I followed this: https://www.cyrill-gremaud.ch/howto-disallow-global-anonymous-bind-with-cnconfig/

**Comment by hirunatan** [comment]
Thanks for the issue, @ldidry. It seems that this case was not foreseen. We'll try to address this as soon as possible.

**Comment by niwinz** [comment]
I'm working on it today and the current ldap auth backend has many bugs; I hope that with my changes this will be fixed.

**Comment by ldidry** [comment]
Thanks! :+1: 

Good luck :crossed_fingers:

**Comment by niwinz** [comment]
Many fixes are landed on the latest release, but the documentation is still missing; I will update this issue when the documentation is ready.

**Comment by ldidry** [comment]
\o/
Thanks!

**Comment by ldidry** [comment]
I pulled the new containers and updated my docker-compose.yaml, it works! Thanks again :clap: :clap: :clap:
