### ISSUE TITLE
Cannot login/register

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#77]
I'm getting "Unable to connect to backend server" message.
In the console:

`XMLHttpRequest cannot load https://test.uxbox.io/api/auth/token. Response for preflight is invalid (redirect)`

`'on-error: {:status 0, :payload ""}
uxbox$main$ui$on_error @ ui.js:39'`

`undefined
uxbox$main$ui$on_error @ ui.js:41`

However, I can login to the demo site.

**Comment by niwinz** [comment]
Yeah, we have done some changes in our servers and the default config on the uxbox repo points to wrong dns. I've pushed a fix for that, just restart the figwheel process after pull.

**Comment by studiospring** [comment]
Great. Thanks.

**Comment by aolko** [comment]
![image](https://user-images.githubusercontent.com/581458/112994628-1e446f00-9173-11eb-943a-fe0b79756510.png)
same here, except a bit different
```
ui.cljs:293 Internal error:
ui.cljs:294 hint: Ya is not a function
ui.cljs:298 TypeError: Ya is not a function
    at OH.f.send (array.js:584)
    at http.cljs:102
    at r._subscribe (core.cljs:129)
    at r._trySubscribe (Observable.js:35)
    at r.subscribe (Observable.js:30)
    at map.js:10
    at e.<anonymous> (lift.js:15)
    at r.subscribe (Observable.js:27)
    at Object.c.mergeInternals (mergeInternals.js:41)
    at mergeMap.js:18
ui.cljs:299 stack: TypeError: Ya is not a function
    at OH.f.send (https://design.penpot.app/js/shared.cc92e4b….js:2626:232)
    at https://design.penpot.app/js/shared.cc92e4b….js:2637:390
    at r._subscribe (https://design.penpot.app/js/shared.cc92e4b….js:2509:228)
    at r._trySubscribe (https://design.penpot.app/js/shared.cc92e4b….js:542:288)
    at r.subscribe (https://design.penpot.app/js/shared.cc92e4b….js:542:206)
    at https://design.penpot.app/js/shared.cc92e4b….js:661:184
    at e.<anonymous> (https://design.penpot.app/js/shared.cc92e4b….js:545:296)
    at r.subscribe (https://design.penpot.app/js/shared.cc92e4b….js:542:122)
    at Object.c.mergeInternals (https://design.penpot.app/js/shared.cc92e4b….js:676:46)
    at https://design.penpot.app/js/shared.cc92e4b….js:677:263
```

**Comment by niwinz** [comment]
@aolko I suggest you open a new issue, providing more details (the issue template may help you).

Without additional info and posting on probably on unrelated and **old** (2017) issue will not help to fix this possible issue.
