### ISSUE TITLE
java.lang.RuntimeException: could not start [#'uxbox.config/secret]

### ISSUE THREAD

**Issue by psdp** [penpot/penpot#99]
Trying to run the backend with `lein run` but failed with an exception output below:

```
WARNING: Inst already refers to: #'clojure.core/Inst in namespace: schema.core, being replaced by: #'schema.core/Inst
Exception in thread "main" java.lang.RuntimeException: could not start [#'uxbox.config/secret] due to, compiling:(/tmp/form-init5741804944757601637.clj:1:73)
        at clojure.lang.Compiler.load(Compiler.java:7442)
        at clojure.lang.Compiler.loadFile(Compiler.java:7368)
        at clojure.main$load_script.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invokeStatic(main.clj:279)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invokeStatic(main.clj:310)
        at clojure.main$null_opt.invokeStatic(main.clj:344)
        at clojure.main$null_opt.invoke(main.clj:341)
        at clojure.main$main.invokeStatic(main.clj:423)
        at clojure.main$main.doInvoke(main.clj:386)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: could not start [#'uxbox.config/secret] due to
        at mount.core$up$fn__655.invoke(core.cljc:92)
        at mount.core$up.invokeStatic(core.cljc:92)
        at mount.core$up.invoke(core.cljc:90)
        at mount.core$bring.invokeStatic(core.cljc:210)
        at mount.core$bring.invoke(core.cljc:202)
        at mount.core$start.invokeStatic(core.cljc:252)
        at mount.core$start.doInvoke(core.cljc:244)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at uxbox.main$_main.invokeStatic(main.clj:66)
        at uxbox.main$_main.doInvoke(main.clj:64)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at user$eval15.invokeStatic(form-init5741804944757601637.clj:1)
        at user$eval15.invoke(form-init5741804944757601637.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6978)
        at clojure.lang.Compiler.eval(Compiler.java:6968)
        at clojure.lang.Compiler.load(Compiler.java:7430)
        ... 12 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.bouncycastle.crypto.digests.Blake2bDigest.doFinal(Unknown Source)
        at buddy.core.hash$eval1585$fn__1590.invoke(hash.clj:81)
        at buddy.core.hash$eval1540$fn__1552$G__1531__1557.invoke(hash.clj:67)
        at buddy.core.hash$hash_plain_data.invokeStatic(hash.clj:124)
        at buddy.core.hash$hash_plain_data.invoke(hash.clj:120)
        at buddy.core.hash$eval1604$fn__1605.invoke(hash.clj:144)
        at buddy.core.hash$eval1508$fn__1509$G__1499__1516.invoke(hash.clj:64)
        at buddy.core.hash$digest.invokeStatic(hash.clj:171)
        at buddy.core.hash$digest.invoke(hash.clj:167)
        at buddy.core.hash$blake2b_256.invokeStatic(hash.clj:191)
        at buddy.core.hash$blake2b_256.invoke(hash.clj:187)
        at uxbox.config$initialize_secret.invokeStatic(config.clj:82)
        at uxbox.config$initialize_secret.invoke(config.clj:76)
        at uxbox.config$eval1771$fn__1772.invoke(config.clj:85)
        at mount.core$record_BANG_.invokeStatic(core.cljc:86)
        at mount.core$record_BANG_.invoke(core.cljc:85)
        at mount.core$up$fn__655.invoke(core.cljc:93)
        ... 28 more
```

**Comment by madmath03** [comment]
Hi @psdp ,

I'm not sure about the root cause of your issue, but there are a lot changes in progress on the master branch and lein is not used at the moment to run the backend.
Could you try the command `./manage.sh run-devenv` and share the results ?

If you only want to run the backend without the full docker devenv, you could take a look at how the devenv starts the backend and reproduce locally:
https://github.com/uxbox/uxbox/blob/712269aa35a6b30d8743cf2e8338fb81240c89f3/docker/devenv/files/start.sh#L12-L14

**Comment by psdp** [comment]
Thanks! I will give it a try.
